/**
 * This file is AUTO GENERATED by [msw-auto-mock](https://github.com/dhlab-org/msw-auto-mock)
 * Feel free to commit/edit it as you need.
 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export type TApiEndpoints = {
  "/login": "POST";
  "/users": "GET" | "POST";
  "/users/:id": "GET";
  "/posts": "GET" | "POST";
  "/posts/:id": "GET" | "PUT" | "DELETE";
  "/posts/:postId/comments": "GET" | "POST";
  "/comments/:id": "PUT" | "DELETE";
};

export type TApiPaths = keyof TApiEndpoints;

export type TApiMethods<T extends TApiPaths> = TApiEndpoints[T];

export type TApiStatusCodes = {
  "/login": {
    POST: 200 | 400 | 401;
  };
  "/users": {
    GET: 200;
    POST: 201 | 400;
  };
  "/users/:id": {
    GET: 200 | 404;
  };
  "/posts": {
    GET: 200;
    POST: 201 | 400;
  };
  "/posts/:id": {
    GET: 200 | 404;
    PUT: 200 | 404;
    DELETE: 204 | 404;
  };
  "/posts/:postId/comments": {
    GET: 200;
    POST: 201 | 404;
  };
  "/comments/:id": {
    PUT: 200 | 404;
    DELETE: 204 | 404;
  };
};

export type TScenarioConfig = {
  [scenarioId: string]: {
    description: string;
    api: {
      [K in TApiPaths]?: {
        [M in TApiMethods<K>]?:
          | {
              status: TApiStatusCodes[K][M];
              allowCustomStatus?: boolean;
            }
          | {
              status: number;
              allowCustomStatus: true;
            };
      };
    };
  };
};
