// 📝 Auto-generated by E2E-Autogen
// 🔧 Generated from: TC-2.1, TC-2.2

import { test } from "@playwright/test";

test.skip("[TC-2.1] 게시글 목록 > 게시글 조회 성공", async ({ page }) => {
  await test.step.skip("[TC-2.1.1] 게시글 목록 페이지 로드 -> 제목(블로그 포스트)이 표시되어야 한다", async () => {
      // 📍 UI Path: /posts

      // 🎬 When: 게시글 목록 페이지 로드
    
      // ✅ Then: 제목(블로그 포스트)이 표시되어야 한다

    });

  await test.step.skip("[TC-2.1.2] 게시글이 1개 이상 표시되어야 한다", async () => {
      
          
      // ✅ Then: 게시글이 1개 이상 표시되어야 한다

    });

  await test.step.skip("[TC-2.1.3] 첫번째 게시글을 클릭한다 -> 제목이 표시되어야 한다", async () => {
      // 📍 UI Path: /:postId

      // 🎬 When: 첫번째 게시글을 클릭한다
    
      // ✅ Then: 제목이 표시되어야 한다

    });
});

test.skip("[TC-2.2] 존재하지 않는 게시글에 접근했을 때 메시지가 떠야 한다", async ({ page }) => {
  await test.step.skip("[TC-2.2.1] 존재하지 않는 게시글 url 접근 -> 메시지(게시글을 찾을 수 없습니다)가 떠야 한다", async () => {
      // 📍 UI Path: /:postId

      // 🎬 When: 존재하지 않는 게시글 url 접근
    
      // ✅ Then: 메시지(게시글을 찾을 수 없습니다)가 떠야 한다

    });
});